# See: https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/exampleSite/config.toml

baseURL = "https://conreality.blog/"
languageCode = "en-us"
title = "Conreality Blog"
theme = "bootstrap4-blog"
paginate = 5
copyright = " "

[taxonomies]
  category = "products"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:filename"
  page = "/:filename"

[params]
  author = "Conreality Team"
  description = "The official Conreality project blog."
  header_visible = true
  date_format = "Mon Jan 02, 2006"
  disable_sri = true

[params.sidebar]
  about = "[**Conreality**](https://conreality.com) is an augmented-reality, live-action wargame platform currently in development."
  num_recent_posts = 2

[params.social]
  twitter = "ConrealityGame"

[menu]

[[menu.navbar]]
  name = "Categories"
  url = "/categories/"

[[menu.navbar]]
  name = "Tags"
  url = "/tags/"

[[menu.sidebar]]
  name = "Arto on Twitter"
  url = "https://twitter.com/bendiken"

[[menu.sidebar]]
  name = "Dan on Twitter"
  url = "https://twitter.com/DanKomorny"
